import type { Metadata } from "next";
import { Bodoni_Moda, Cinzel } from "next/font/google";
import "./globals.css";


const cinzel = Cinzel({
  variable: "--font-cinzel",
  subsets: ["latin"],
});

const bodoni = Bodoni_Moda({
  variable: "--font-bodoni",
  subsets: ["latin"],
  style: ["italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cinzel.variable} ${bodoni.variable} antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
