import type { Metadata } from "next";
import { Bodoni_Moda, Cinzel, DM_Sans, Roboto } from "next/font/google";
import "./globals.css";


const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

const bodoni = DM_Sans({
  variable: "--font-dm-sans",
  subsets: ["latin"],
  style: ["italic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.variable} ${bodoni.variable} antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
